import Head from "next/head";
import { Inter } from "next/font/google";
import styled from "@xstyled/styled-components";
import { forwardRef } from "react";

const inter = Inter({ subsets: ["latin"] });

const ButtonStyled = styled.buttonBox`
  border-radius: md;
  font-weight: semibold;
  transition: default;
  background-color: emerald-500;
  color: #fff;

  @media (min-width: md) {
    font-size: lg;
  }
`;

// This is strange code but let's pretend that we need some additional
// logic here and styled component is not enough
export const Button = forwardRef<
  HTMLButtonElement,
  React.ComponentProps<typeof ButtonStyled>
>(({ children, ...props }, ref) => {
  return (
    <ButtonStyled ref={ref} {...props}>
      {children}
    </ButtonStyled>
  );
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Button as="a" href="http://google.com">
          123
        </Button>
      </main>
    </>
  );
}
